### ISSUE TITLE
Export Stil: DIN

### ISSUE THREAD

**Issue by juame** [rothsandro/Quotly#2]
Die Abteilungen Architektur und Innenarchitektur der HSLU scheinen die DIN-Norm für die Zitier- und Quellenangaben zu nutzen. Siehe Wikipedia: [ISO 690](https://de.wikipedia.org/wiki/ISO_690).

Könnte man DIN bei Quotly als weiterer Export Stil hinzufügen?

**Comment by rothsandro** [comment]
Andere Exportformate als APA (angepasst an die HSLU) sind aktuell nicht geplant.
